package game

import (
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"strings"

	"github.com/kpechenenko/rword"

	"github.com/robbiebyrd/indri/internal/models"
	gameRepo "github.com/robbiebyrd/indri/internal/repo/game"
	scriptRepo "github.com/robbiebyrd/indri/internal/repo/script"
	"github.com/robbiebyrd/indri/internal/services/events"
	"github.com/robbiebyrd/indri/internal/transport"
)

type Service struct {
	gameRepo gameRepo.Storer
	Script   *models.Script
}

// NewService creates a new repository for accessing game data.
func NewService(gameRepo gameRepo.Storer, scriptRepo *scriptRepo.Store) (*Service, error) {
	if gameRepo == nil {
		return nil, errors.New("the game service did not receive a game repo")
	}

	return &Service{
		gameRepo: gameRepo,
		Script:   scriptRepo.Get(),
	}, nil
}

// New creates a new game, with or without a Code.
func (gs *Service) New(gameCode string, private bool) (*models.Game, error) {
	if gameCode == "" {
		// If no gameCode was given, then we will try to create a random one
		autogenCode, err := gs.getAutoGeneratedGameCode()
		if err != nil {
			return nil, err
		}

		gameCode = autogenCode
	}

	if gs.Exists(gameCode) {
		return nil, fmt.Errorf("game with id %s already exists", gameCode)
	}

	log.Printf("creating new game with gameCode %v ", gameCode)

	g, err := gs.gameRepo.New(gameCode, gs.Script, private)
	if err != nil {
		return nil, err
	}

	return g, nil
}

// Get will fetch game data for a specific game ID.
func (gs *Service) Get(id string) (*models.Game, error) {
	g, err := gs.gameRepo.Get(id)
	if err != nil {
		return nil, fmt.Errorf("fetching game %q: %w", id, err)
	}

	return g, nil
}

// GetJSONBytes will fetch game data and return JSON bytes. It will create a game if it doesn't exist.
func (gs *Service) GetJSONBytes(id string) (*[]byte, error) {
	g, err := gs.Get(id)
	if err != nil {
		return nil, err
	}

	gameJSONBytes, err := json.Marshal(gs.Sanitize(g))
	if err != nil {
		return nil, err
	}

	return &gameJSONBytes, nil
}

// GetByCode will fetch game data for a specific game code.
func (gs *Service) GetByCode(gameCode string) (*models.Game, error) {
	if gameCode == "" {
		return nil, fmt.Errorf("game code is empty")
	}

	gameId, err := gs.gameRepo.GetIDHex(gameCode)
	if err != nil {
		return nil, fmt.Errorf("resolving game code %q: %w", gameCode, err)
	}

	g, err := gs.gameRepo.Get(*gameId)
	if err != nil {
		return nil, fmt.Errorf("fetching game %q: %w", gameCode, err)
	}

	return g, nil
}

// Fetch retrieves game data for a specific game ID and returns an error if not found.
func (gs *Service) Fetch(id string) (*models.Game, error) {
	if id == "" {
		return nil, fmt.Errorf("id is  nil")
	}

	return gs.gameRepo.Get(id)
}

// FindOpen
func (gs *Service) FindOpen(limit int) ([]*models.Game, error) {
	return gs.gameRepo.FindOpen(limit)
}

// FetchByCode retrieves game data for a specific game code and returns an error if not found.
func (gs *Service) FetchByCode(gameCode string) (*models.Game, error) {
	if gameCode == "" {
		return nil, fmt.Errorf("game code is required")
	}

	gameId, err := gs.gameRepo.GetIDHex(gameCode)
	if err != nil {
		return nil, err
	}

	return gs.gameRepo.Get(*gameId)
}

// Exists checks to see if a game with the given ID already exists.
func (gs *Service) Exists(id string) bool {
	if id == "" {
		return false
	}

	exists, err := gs.gameRepo.Exists(id)
	if err != nil {
		return false
	}

	return exists
}

// Update saves game data to the repository.
func (gs *Service) Update(id string, game *models.UpdateGame) error {
	if id == "" {
		return fmt.Errorf("game code cannot be empty")
	}

	err := gs.gameRepo.Update(id, game)
	if err != nil {
		return err
	}

	return nil
}

// Reset a game to its defaults.
func (gs *Service) Reset() *models.Game {
	// TODO: reload a game from a script
	return nil
}

// Sanitize removes private items so a keyframe never exposes private data.
// It matches events.SanitizeDelta, so keyframes and deltas agree on visibility.
func (gs *Service) Sanitize(game *models.Game) *models.Game {
	game.PrivateData = nil
	game.Stage.PrivateData = nil

	for i, g := range game.Stage.Scenes {
		g.PrivateData = nil
		game.Stage.Scenes[i] = g
	}

	for i, t := range game.Teams {
		t.PrivateData = nil
		game.Teams[i] = t
	}

	for i, p := range game.Players {
		p.PrivateData = nil
		game.Players[i] = p
	}

	return game
}

// slimKeyframe returns a sanitized, layout-stripped copy of the game. Its schema
// version is the layout hash, which stays the same for the life of the game.
func (gs *Service) slimKeyframe(g *models.Game, layoutHash string) (events.KeyframeWrapper, error) {
	raw, err := json.Marshal(g)
	if err != nil {
		return events.KeyframeWrapper{}, err
	}
	var clone models.Game
	if err := json.Unmarshal(raw, &clone); err != nil {
		return events.KeyframeWrapper{}, err
	}
	slim := gs.Sanitize(&clone)
	if slim.PublicData != nil {
		delete(slim.PublicData, "layout")
	}
	return events.KeyframeWrapper{SV: layoutHash, Game: slim}, nil
}

// WriteKeyframe sends a LayoutFrame followed by a slim keyframe to a single connection.
func (gs *Service) WriteKeyframe(conn transport.Conn, g *models.Game, layoutHash string, layoutData map[string]interface{}) error {
	layoutFrame := events.LayoutFrame{O: events.OpLayout, V: layoutHash, Data: layoutData}
	if err := transport.WriteEncoded(conn, layoutFrame); err != nil {
		return err
	}
	wrapper, err := gs.slimKeyframe(g, layoutHash)
	if err != nil {
		return err
	}
	return transport.WriteEncoded(conn, wrapper)
}

// WriteSlimKeyframe sends a slim keyframe without a layout frame — used for refresh.
func (gs *Service) WriteSlimKeyframe(conn transport.Conn, g *models.Game, layoutHash string) error {
	wrapper, err := gs.slimKeyframe(g, layoutHash)
	if err != nil {
		return err
	}
	return transport.WriteEncoded(conn, wrapper)
}

func (gs *Service) DisconnectPlayer(id string, slotId string) error {
	return gs.gameRepo.DisconnectPlayer(id, slotId)
}

func (gs *Service) RemovePlayer(id string, slotId string) error {
	return gs.gameRepo.RemovePlayer(id, slotId)
}

func (gs *Service) getAutoGeneratedGameCode() (string, error) {
	for {
		autogenCode, err := gs.makeRandomGameId()
		if err != nil {
			return "", err
		}

		exists, err := gs.gameRepo.Exists(autogenCode)
		if err != nil {
			return "", fmt.Errorf("checking whether game code %q exists: %w", autogenCode, err)
		}

		if !exists {
			return autogenCode, nil
		}
	}
}

func (gs *Service) makeRandomGameId() (string, error) {
	rw, err := rword.New()
	if err != nil {
		return "", err
	}

	id := strings.ReplaceAll(rw.Str(4)+rw.Str(4)+rw.Str(4), " ", "-")

	return id, nil
}
