package game

import (
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"strings"

	"github.com/kpechenenko/rword"

	"github.com/robbiebyrd/indri/internal/models"
	gameRepo "github.com/robbiebyrd/indri/internal/repo/game"
	scriptRepo "github.com/robbiebyrd/indri/internal/repo/script"
	luaService "github.com/robbiebyrd/indri/internal/services/lua"
)

// LifecycleEmitter tells a game script that something happened to a game.
//
// It returns nothing, and that is the contract rather than an oversight: a
// lifecycle event is raised after the write that caused it has committed, so a
// subscriber's bug must not be able to fail a create, a join or a leave. The
// emitter logs what goes wrong and the originating action carries on.
//
// Narrow and free of Lua for the same reason lua.GameMutator is narrow and free
// of MongoDB: *lua.Engine satisfies it, and this package does not import the
// script engine to say so.
type LifecycleEmitter interface {
	EmitLifecycle(event, gameID string, subject map[string]interface{})
}

type Service struct {
	gameRepo gameRepo.Storer
	Script   *models.Script

	// Lifecycle is where this service's events go. It is an exported field set
	// at boot rather than a constructor argument, the same shape as
	// lua.Engine.Dispatch and for the same reason: the script engine is built
	// after the services it edits through, so the two are tied together once
	// both exist. A nil one raises nothing, which is what a server running no
	// scripts wants.
	Lifecycle LifecycleEmitter
}

// NewService creates a new repository for accessing game data.
func NewService(gameRepo gameRepo.Storer, scriptRepo *scriptRepo.Store) (*Service, error) {
	if gameRepo == nil {
		return nil, errors.New("the game service did not receive a game repo")
	}

	return &Service{
		gameRepo: gameRepo,
		Script:   scriptRepo.Get(),
	}, nil
}

// emit raises one lifecycle event, if anything is there to hear it.
//
// Called only after the write it describes has committed. Every call site pairs
// it with a committed flag the store reported rather than with a nil error,
// because a mutation that aborted also returns nil and an event about a write
// that did not happen is worse than no event at all.
func (gs *Service) emit(event, gameID string, subject map[string]interface{}) {
	if gs.Lifecycle == nil {
		return
	}

	gs.Lifecycle.EmitLifecycle(event, gameID, subject)
}

// New creates a new game, with or without a Code.
func (gs *Service) New(gameCode string, private bool) (*models.Game, error) {
	if gameCode == "" {
		// If no gameCode was given, then we will try to create a random one
		autogenCode, err := gs.getAutoGeneratedGameCode()
		if err != nil {
			return nil, err
		}

		gameCode = autogenCode
	}

	if gs.Exists(gameCode) {
		return nil, fmt.Errorf("game with id %s already exists", gameCode)
	}

	log.Printf("creating new game with gameCode %v ", gameCode)

	g, err := gs.gameRepo.New(gameCode, gs.Script, private)
	if err != nil {
		return nil, err
	}

	// After the insert, never before it: a subscriber's first act is usually to
	// read or edit the game it was told about, and a game that is not stored yet
	// is a game it cannot find. An insert has no version fence to lose, so its
	// nil error is the commit.
	gs.emit(luaService.LifecycleGameCreated, g.ID, map[string]interface{}{
		"code":    g.Code,
		"private": g.Private,
	})

	return g, nil
}

// Get will fetch game data for a specific game ID.
func (gs *Service) Get(id string) (*models.Game, error) {
	g, err := gs.gameRepo.Get(id)
	if err != nil {
		return nil, fmt.Errorf("fetching game %q: %w", id, err)
	}

	return g, nil
}

// GetJSONBytes will fetch game data and return JSON bytes. It will create a game if it doesn't exist.
func (gs *Service) GetJSONBytes(id string) (*[]byte, error) {
	g, err := gs.Get(id)
	if err != nil {
		return nil, err
	}

	gameJSONBytes, err := json.Marshal(gs.Sanitize(g))
	if err != nil {
		return nil, err
	}

	return &gameJSONBytes, nil
}

// GetByCode will fetch game data for a specific game code.
func (gs *Service) GetByCode(gameCode string) (*models.Game, error) {
	if gameCode == "" {
		return nil, fmt.Errorf("game code is empty")
	}

	gameId, err := gs.gameRepo.GetIDHex(gameCode)
	if err != nil {
		return nil, fmt.Errorf("resolving game code %q: %w", gameCode, err)
	}

	g, err := gs.gameRepo.Get(*gameId)
	if err != nil {
		return nil, fmt.Errorf("fetching game %q: %w", gameCode, err)
	}

	return g, nil
}

// Fetch retrieves game data for a specific game ID and returns an error if not found.
func (gs *Service) Fetch(id string) (*models.Game, error) {
	if id == "" {
		return nil, fmt.Errorf("id is  nil")
	}

	return gs.gameRepo.Get(id)
}

// FindOpen
func (gs *Service) FindOpen(limit int) ([]*models.Game, error) {
	return gs.gameRepo.FindOpen(limit)
}

// FetchByCode retrieves game data for a specific game code and returns an error if not found.
func (gs *Service) FetchByCode(gameCode string) (*models.Game, error) {
	if gameCode == "" {
		return nil, fmt.Errorf("game code is required")
	}

	gameId, err := gs.gameRepo.GetIDHex(gameCode)
	if err != nil {
		return nil, err
	}

	return gs.gameRepo.Get(*gameId)
}

// Exists checks to see if a game with the given ID already exists.
func (gs *Service) Exists(id string) bool {
	if id == "" {
		return false
	}

	exists, err := gs.gameRepo.Exists(id)
	if err != nil {
		return false
	}

	return exists
}

// Update saves game data to the repository.
func (gs *Service) Update(id string, game *models.UpdateGame) error {
	if id == "" {
		return fmt.Errorf("game code cannot be empty")
	}

	err := gs.gameRepo.Update(id, game)
	if err != nil {
		return err
	}

	return nil
}

// Reset a game to its defaults.
func (gs *Service) Reset() *models.Game {
	// TODO: reload a game from a script
	return nil
}

// Sanitize removes private items so a keyframe never exposes private data.
// It matches events.SanitizeDelta, so keyframes and deltas agree on visibility.
func (gs *Service) Sanitize(game *models.Game) *models.Game {
	game.PrivateData = nil
	game.Stage.PrivateData = nil

	for i, g := range game.Stage.Scenes {
		g.PrivateData = nil
		game.Stage.Scenes[i] = g
	}

	for i, t := range game.Teams {
		t.PrivateData = nil
		game.Teams[i] = t
	}

	for i, p := range game.Players {
		p.PrivateData = nil
		game.Players[i] = p
	}

	return game
}

func (gs *Service) ConnectPlayer(id string, teamId string, userId string, displayName string) error {
	log.Printf("Adding player %v to game lobby\n", userId)

	// The flag, not the error: a player who is already in the game joined once
	// and must not raise player:joined again on every reconnect.
	added, err := gs.gameRepo.AddPlayerResult(id, userId, displayName)
	if err != nil {
		log.Printf("Error adding player %v to game lobby: %v\n", userId, err)
	}

	if err := gs.placeOnTeam(id, teamId, userId); err != nil {
		return err
	}

	// Raised here rather than beside AddPlayerResult so that a subscriber
	// reading the game finds the player where the join left them — on their
	// team — rather than half-joined.
	if added {
		gs.emit(luaService.LifecyclePlayerJoined, id, map[string]interface{}{
			"userId": userId,
			"teamId": teamId,
		})
	}

	return nil
}

// placeOnTeam puts a joining player on the team they asked for, whichever of
// the four cases they are in.
func (gs *Service) placeOnTeam(id string, teamId string, userId string) error {
	switch {
	case gs.gameRepo.HasPlayerOnTeam(id, teamId, userId):
		log.Printf("Player %v is on team %v\n", userId, teamId)
		return gs.gameRepo.ConnectPlayer(id, userId)
	case gs.gameRepo.PlayerOnATeam(id, userId):
		log.Printf("Player %v is already on a team, changing\n", userId)
		return gs.gameRepo.ChangePlayerTeam(id, teamId, userId)
	case teamId != "":
		log.Printf("Adding player %v to team %v\n", userId, teamId)
		return gs.gameRepo.AddPlayerToTeam(id, teamId, userId)
	default:
		return nil
	}
}

func (gs *Service) DisconnectPlayer(id string, userId string) error {
	if gs.gameRepo.HasPlayer(id, userId) {
		return gs.gameRepo.DisconnectPlayer(id, userId)
	}

	return nil
}

func (gs *Service) RemovePlayer(id string, userId string) error {
	// Removing somebody who is not in the game writes an unchanged document and
	// is not a departure; the store answers which it was. A leave and a kick
	// racing therefore raise player:left once between them, not twice.
	removed, err := gs.gameRepo.RemovePlayerResult(id, userId)
	if err != nil {
		return err
	}

	if removed {
		gs.emit(luaService.LifecyclePlayerLeft, id, map[string]interface{}{"userId": userId})
	}

	return nil
}

func (gs *Service) getAutoGeneratedGameCode() (string, error) {
	for {
		autogenCode, err := gs.makeRandomGameId()
		if err != nil {
			return "", err
		}

		exists, err := gs.gameRepo.Exists(autogenCode)
		if err != nil {
			return "", fmt.Errorf("checking whether game code %q exists: %w", autogenCode, err)
		}

		if !exists {
			return autogenCode, nil
		}
	}
}

func (gs *Service) makeRandomGameId() (string, error) {
	rw, err := rword.New()
	if err != nil {
		return "", err
	}

	id := strings.ReplaceAll(rw.Str(4)+rw.Str(4)+rw.Str(4), " ", "-")

	return id, nil
}
