version: '3.8'

services:
  mongodb:
    image: mongo:latest # Use the official MongoDB image
    container_name: my_mongodb_instance
    env_file:
      - .env
    ports:
      - "${INDRI_MONGOPORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${INDRI_MONGOUSERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${INDRI_MONGOPASSWORD}
    volumes:
      - mongodb_data:/data/db
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${INDRI_REDISPASSWORD}
      - ALLOW_EMPTY_PASSWORD=${INDRI_REDISEMPTYPASSWORD:-no}
    ports:
      - '${INDRI_REDISPORT:-6379}:6379'

volumes:
  mongodb_data:
